### ISSUE TITLE
'Multi_OLEDDrawLine' was not declared in this scope

### ISSUE THREAD

**Issue by tehniq3** [bitbank2/Multi_OLED#12]
I test the "simple_demo"sketch with 4 OLD displays ( see https://youtu.be/hska7K8LrRY video), but "line_demo"sketch for graphic primitive I saw this erros:
C:\Users\Nicu\AppData\Local\Temp\arduino_modified_sketch_959437\line_demo.ino: In function 'void loop()':
line_demo:45:5: error: 'Multi_OLEDDrawLine' was not declared in this scope
     Multi_OLEDDrawLine(1, x1, y1, x2, y2);
     ^~~~~~~~~~~~~~~~~~
C:\Users\Nicu\AppData\Local\Temp\arduino_modified_sketch_959437\line_demo.ino:45:5: note: suggested alternative: 'Multi_OLEDFill'
     Multi_OLEDDrawLine(1, x1, y1, x2, y2);
     ^~~~~~~~~~~~~~~~~~
     Multi_OLEDFill
Using library Multi_BitBang-master at version 1.0.0 in folder: C:\Users\Nicu\Documents\Arduino\libraries\Multi_BitBang-master 
Using library Multi_OLED-master at version 1.0.0 in folder: C:\Users\Nicu\Documents\Arduino\libraries\Multi_OLED-master 
exit status 1
'Multi_OLEDDrawLine' was not declared in this scope

can you help with a hint?
I test with Arduino NaNo board and 4 OLED display (128x64 - 0x3C adress)

PS: main target is to recreate this project from https://youtu.be/uC9bvJ73Ljc

**Comment by bitbank2** [comment]
The function you're trying to use is disabled on AVR targets because they generally don't have enough RAM to hold a backing buffer for the display. If you're using a regular Nano (2K RAM) and drawing on 4 displays (1K buffer needed for each), you won't have enough RAM. You can do direct drawing of characters to the OLED without the need for a backing buffer, but some functions need to draw into RAM first.
