### ISSUE TITLE
Not an Issue - Just a BIG Thank-You !!! + Quick Question :)

### ISSUE THREAD

**Issue by offtherails2010** [bitbank2/Multi_OLED#2]
**dude ! YOURE AMAZING !!!**

i cant believe how awesome youve gone to such lengths to include especially what ive been searching for - for DAYS/WEEKS - **the 0.49 inch OLED** displays !!

Quick Question if i may please please:

Would these libraries also work with the newest (i assume its new) **the 0.42 inch** OLED (Aliexpress, £1.50 no PCB, 16 pin, 3.3v, 72x40 Resolution)

**Thanks loads in advance and once again - You are A MIRACLE WORKER !!!!**

**Your Skill is just - PRICELESS !!!**

PS - i tried to leave this comment on your blogspot webpage but i keep getting; **

> 403 Forbidden

**, after clicking publish :(

it would had been so awesome if you had your comments enabled on that site, but i had to find a way to thank you for doing such amazing work and with the sheer skill of being able to make libraries for the arduino and accommodating extra platforms that use the arduino IDE, **Youre Simply BRILLIANT !!!!!!!!!**

**Comment by bitbank2** [comment]
Thanks for the effusive praise :)
I'm glad you find the code useful - that's why I share it. I thought comments were open, but I just saw that they require a Google ID, so I enabled them for everyone. Please try again to comment on my blog. I haven't seen those displays before (I just ordered a few). Some minor changes will probably be needed to make them work properly. You can try using the 128x64 or 128x32 settings and see what happens until I get my hands on them and update the code. They will probably arrive in 3-4 weeks and then I'll update all of my SSD1306 code to support them.
